homeassistant:
  name: Home
  latitude: !secret latitude
  longitude: !secret longitude
  temperature_unit: C
  time_zone: Europe/Amsterdam
  customize: !include customize.yaml

#device_tracker: !include device_tracker.yaml
mqtt:
  broker: !secret mqtt_host
  port: 1883
  client_id: hass01
  keepalive: 60
group: !include groups.yaml

media_player:
  platform: cast
  host: !secret livingroom_cast_host

light:
  platform: limitlessled
  host: !secret limitlessled_host
  group_1_name: Living Room
  group_2_name: Office

switch 1:
  platform: transmission
  host: !secret transmission_host

sensor: !include sensors.yaml

history:

logbook:

sun:

updater:
