homeassistant:
  name: Home
  latitude: !include latitude.yaml
  longitude: !include longitude.yaml
  temperature_unit: C
  time_zone: Europe/Amsterdam
  customize: !include customize.yaml

device_tracker: !include device_tracker.yaml
mqtt: !include mqtt.yaml
group: !include groups.yaml

media_player:
  platform: cast
  host: 192.168.50.80

light:
  platform: limitlessled
  host: 192.168.50.81
  group_1_name: Living Room
  group_2_name: Office

switch 1:
  platform: transmission
  host: 192.168.50.9

sensor: !include sensors.yaml

history:

logbook:

sun:
