- platform: mqtt
  state_topic: "devices/fd8b87e0/temperature/temperature"
  name: "Temperature living room"
  qos: 0
  unit_of_measurement: "C"

- platform: mqtt
  state_topic: "devices/fd8b87e0/humidity/humidity"
  name: "Humidity living room"
  qos: 0
  unit_of_measurement: "%"

- platform: mqtt
  state_topic: "devices/e0c74fe0/temperature/temperature"
  name: "Temperature bedroom"
  qos: 0
  unit_of_measurement: "C"

- platform: mqtt
  state_topic: "devices/e0c74fe0/humidity/humidity"
  name: "Humidity bedroom"
  qos: 0
  unit_of_measurement: "%"

- platform: speedtest
  monitored_conditions:
    - ping
    - download
    - upload

- platform: transmission
  host: 192.168.50.9
  monitored_variables:
    - current_status
    - download_speed
    - upload_speed
